table _Calculations
	lineageTag: 7ce3379e-12e7-4f7d-98ec-6a7aee3db1f6

	measure 'Total Defect Qty' = SUM('Supplier Fact'[Total Defect Qty])
		formatString: #,0
		displayFolder: Defect Quantity
		lineageTag: bbe68671-3073-4385-a619-13916eab3e48

	measure 'Total Downtime Minutes' = SUM('Supplier Fact'[Total Downtime Minutes])
		formatString: 0
		displayFolder: Downtime
		lineageTag: 695dca3b-5bb6-4074-b696-db0a37cd9645

	measure 'Total Defect Report' = COUNTROWS('Supplier Fact')
		formatString: 0
		displayFolder: Defect Report
		lineageTag: 87e30def-5711-4f7f-a16e-a2009ae386d7

	measure 'Defect Qty SPLY' = CALCULATE([Total Defect Qty], SAMEPERIODLASTYEAR('Date'[Date]))
		formatString: #,0
		displayFolder: Defect Quantity
		lineageTag: 02a2c243-9548-4205-b190-76b5c5b10f18

	measure 'Total Defect Qty PM' = CALCULATE([Total Defect Qty], PARALLELPERIOD('Date'[Date], -1, MONTH))
		formatString: #,0
		displayFolder: Defect Quantity
		lineageTag: 426c0b8c-59e7-46e1-b569-d2bb502d7b36

	measure YOYGrowthDefectQty = ```
			DIVIDE([Total Defect Qty] - [Defect Qty SPLY], [Defect Qty SPLY], 0) 
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Defect Quantity
		lineageTag: f8bb6dad-f6e9-4352-a1b0-93646c8caa2b

	measure MOMGrowthDowntimeCost = ```
			DIVIDE([Downtime Cost/Hr] - [Total Downtime Cost PM], [Total Downtime Cost PM], 0) 
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Downtime Cost
		lineageTag: a8df1bdb-ee8b-41b9-8cf0-cdaaa7ea51e5

	measure 'Total Downtime Hours SPLY' = CALCULATE([Total Downtime Hours], SAMEPERIODLASTYEAR('Date'[Date]))
		formatString: 0
		displayFolder: Downtime
		lineageTag: 9fa1e337-4d63-490a-b14f-12c7b06b2caa

	measure 'Total Downtime Hours' = [Total Downtime Minutes]/60
		displayFolder: Downtime
		lineageTag: 4def1b95-b766-4317-828e-432b4cf6e79a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total DownTime Hours PM' = CALCULATE([Total Downtime Hours], PARALLELPERIOD('Date'[Date], -1,MONTH))
		displayFolder: Downtime
		lineageTag: 9ba9cecc-3799-4f2d-bd04-efc1843f7dde

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure YOYGrowthDowntimeHours = DIVIDE([Total Downtime Hours] - [Total Downtime Hours SPLY],[Total Downtime Hours SPLY], 0)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Downtime
		lineageTag: 288e74a4-7b53-4d85-950b-e810f693899b

	measure MOMGrowthDowntimeHours = DIVIDE([Total Downtime Hours] - [Total DownTime Hours PM], [Total DownTime Hours PM], 0)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Downtime
		lineageTag: 8e4d8302-2ff0-4e00-a7c8-0c6a75e8f196

	measure 'MOM Defect Quantity Trend Icon' =
			
			VAR PositiveIcon = UNICHAR(9650)
			VAR NegativeIcon = UNICHAR(9660)
			VAR Choice = IF([MOMGrowthDefectQty] > 0, PositiveIcon, NegativeIcon)
			VAR Display = Choice & " " & FORMAT([MOMGrowthDefectQty], "0.00%")
			RETURN Display
		displayFolder: Defect Quantity
		lineageTag: 88102928-7c29-4730-a704-ca0febf27ba3

	measure 'MOM Defect Quantity Trend Colour' = IF([MOMGrowthDefectQty] > 0, "Red", "Green")
		displayFolder: Defect Quantity
		lineageTag: d3b1efb9-2d91-47ef-b4ca-97731b9e1b23

	measure 'YOY Defect Quantity Trend Icon' =
			
			VAR PositiveIcon = UNICHAR(9650)
			VAR NegativeIcon = UNICHAR(9660)
			VAR Choice = IF([YOYGrowthDefectQty] > 0, PositiveIcon, NegativeIcon)
			VAR Display = Choice & " " & FORMAT([YOYGrowthDefectQty], "0.00%")
			RETURN Display
		displayFolder: Defect Quantity
		lineageTag: 18906f8b-9101-4416-9f29-f1df0a205ac2

	measure 'YOY Defect Quantity Trend Colour' = IF([YOYGrowthDefectQty] > 0, "Red", "Green")
		displayFolder: Defect Quantity
		lineageTag: a6a25b3e-e91d-411c-bd72-e7ba02904b4d

	measure 'MOM Downtime Hour Trend Icon' =
			
			VAR PositiveIcon = UNICHAR(9650)
			VAR NegativeIcon = UNICHAR(9660)
			VAR Choice = IF([MOMGrowthDowntimeHours] > 0, PositiveIcon, NegativeIcon)
			VAR Display = Choice & " " & FORMAT([MOMGrowthDowntimeHours], "0.00%")
			RETURN Display
		displayFolder: Downtime
		lineageTag: c89fa038-b6a0-4eae-91e3-7438542011ca

	measure 'YOY Downtime Hours Trend Icon' =
			
			VAR PositiveIcon = UNICHAR(9650)
			VAR NegativeIcon = UNICHAR(9660)
			VAR Choice = IF([YOYGrowthDowntimeHours] > 0, PositiveIcon, NegativeIcon)
			VAR Display = Choice & " " & FORMAT([YOYGrowthDowntimeHours], "0.00%")
			RETURN Display
		displayFolder: Downtime
		lineageTag: b0810fe6-b6a9-4d1c-a3f9-485565ad230f

	measure 'Downtime Cost/Hr' = [Total Downtime Hours] * 'Downtime Cost Parameter'[Downtime Cost Value]
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		displayFolder: Downtime Cost
		lineageTag: faf3f2c7-56b4-42ad-a228-b00bef9b88ac

	measure 'MOM Downtime Hour Trend Colour' = IF([MOMGrowthDowntimeCost] > 0, "Red", "Green")
		displayFolder: Downtime
		lineageTag: fe3e1539-1f6c-4a0e-891f-1f40327c7f79

	measure 'YOY Downtime Hour Trend Colour' = IF([YOYGrowthDefectQty] > 0, "Red", "Green")
		displayFolder: Downtime
		lineageTag: 263eec10-c655-4c91-bd45-db179ab463cd

	measure 'Downtime Hour SPLY' = CALCULATE([Downtime Cost/Hr], SAMEPERIODLASTYEAR('Date'[Date]))
		displayFolder: Downtime Cost
		lineageTag: 8ae0d806-30cb-4181-ac6a-7870cd630e53

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Downtime Cost PM' = CALCULATE([Downtime Cost/Hr], PARALLELPERIOD('Date'[Date], -1, MONTH))
		displayFolder: Downtime Cost
		lineageTag: 66aa4972-1d37-424b-8a8e-75102c16e9f5

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure YOYGrowthDowntimeCost = ```
			DIVIDE([Downtime Cost/Hr] - [Downtime Hour SPLY], [Downtime Hour SPLY], 0) 
			```
		displayFolder: Downtime Cost
		lineageTag: f0e5b034-1801-4645-9126-ec9b1be47e05

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure MOMGrowthDefectQty = ```
			DIVIDE([Total Defect Qty] - [Total Defect Qty PM], [Total Defect Qty PM], 0) 
			```
		displayFolder: Defect Quantity
		lineageTag: aff87290-b527-4801-92e0-8994c90dd37e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'MOM Downtime Cost Trend Icon' =
			
			VAR PositiveIcon = UNICHAR(9650)
			VAR NegativeIcon = UNICHAR(9660)
			VAR Choice = IF([MOMGrowthDowntimeCost] > 0, PositiveIcon, NegativeIcon)
			VAR Display = Choice & " " & FORMAT([MOMGrowthDowntimeCost], "0.00%")
			RETURN Display
		displayFolder: Downtime Cost
		lineageTag: cd9ecdf7-dc92-4542-a458-cb8952c769d8

	measure 'MOM Downtime Cost Trend Colour' = IF([MOMGrowthDowntimeCost] > 0, "Red", "Green")
		displayFolder: Downtime Cost
		lineageTag: 56b0ad82-00ca-4add-9588-e370194c1ba3

	measure 'YOY Downtime Cost Trend Icon' =
			
			VAR PositiveIcon = UNICHAR(9650)
			VAR NegativeIcon = UNICHAR(9660)
			VAR Choice = IF([YOYGrowthDowntimeCost] > 0, PositiveIcon, NegativeIcon)
			VAR Display = Choice & " " & FORMAT([YOYGrowthDowntimeCost], "0.00%")
			RETURN Display
		displayFolder: Downtime Cost
		lineageTag: 603128ed-4048-4400-b911-d2d3947fd3c9

	measure 'YOY Downtime Cost Trend Colour' = IF([YOYGrowthDowntimeCost] > 0, "Red", "Green")
		displayFolder: Downtime Cost
		lineageTag: cd94e6af-4ad6-49e8-818a-b727b99ccffe

	measure 'Impact Defect Type' =
			
			VAR Impact = CALCULATE(COUNT('Supplier Fact'[DefectTypeID]), KEEPFILTERS('Defect Type'[Defect Type] = "Impact"))
			VAR Defects = COUNT('Supplier Fact'[DefectTypeID])
			RETURN
			DIVIDE(Impact, Defects)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Defect Type
		lineageTag: fa8d437b-c221-453d-890e-e6666555cc43

	measure 'No Impact Defect Type' =
			
			VAR NoImpact = CALCULATE(COUNT('Supplier Fact'[DefectTypeID]), KEEPFILTERS('Defect Type'[Defect Type] = "No Impact"))
			VAR Defects = COUNT('Supplier Fact'[DefectTypeID])
			RETURN
			DIVIDE(NoImpact, Defects)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Defect Type
		lineageTag: 5f3a99be-bde4-4377-883e-75308b2f56ce

	measure 'Reject Defect Type' =
			
			VAR Reject = CALCULATE(COUNT('Supplier Fact'[DefectTypeID]), KEEPFILTERS('Defect Type'[Defect Type] = "Rejected"))
			VAR Defects = COUNT('Supplier Fact'[DefectTypeID])
			RETURN
			DIVIDE(Reject, Defects)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Defect Type
		lineageTag: 666c38a6-3800-4ce5-ac23-4c11f77b8bcd

	measure 'Rank Vendor by Defect Qty' =
			
			VAR topVendorDefectQty = IF(ISINSCOPE(Vendor[Vendor]),(RANKX(ALL(Vendor[Vendor]), [Total Defect Qty], ,DESC)))
			VAR bottomVendorDefectQty = IF(ISINSCOPE(Vendor[Vendor]),(RANKX(ALL(Vendor[Vendor]), [Total Defect Qty], ,ASC)))
			
			VAR ranking = IF(SELECTEDVALUE(TopBottom[Value]) = "Top", topVendorDefectQty, bottomVendorDefectQty)
			RETURN IF(ranking <= 'Top N Parameter'[Top N Parameter Value], [Total Defect Qty])
		formatString: 0
		displayFolder: Rank
		lineageTag: 9fe973ea-0fa0-4e44-9fab-faec784d1e39

	measure 'Rank Vendor by DownTime Hrs' =
			
			VAR topVendorDownTimeHrs = IF(ISINSCOPE(Vendor[Vendor]),(RANKX(ALL(Vendor[Vendor]), [Total Downtime Hours], ,DESC)))
			VAR bottomVendorDownTimeHrs = IF(ISINSCOPE(Vendor[Vendor]),(RANKX(ALL(Vendor[Vendor]), [Total Downtime Hours], ,ASC)))
			
			VAR ranking = IF(SELECTEDVALUE(TopBottom[Value]) = "Top", topVendorDownTimeHrs, bottomVendorDownTimeHrs)
			
			RETURN IF(ranking <= 'Top N Parameter'[Top N Parameter Value], [Total Downtime Hours])
		displayFolder: Rank
		lineageTag: fadc2fc9-6cec-40fb-bd12-595c6acbaa4b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Risk Category' = ```
			
			VAR CurrentVendor = SELECTEDVALUE(Vendor[Vendor])
			VAR TotalDowntimeHours  = CALCULATE([Total Downtime Hours], FILTER(Vendor,Vendor[Vendor] = CurrentVendor))
			
			RETURN IF([Total Downtime Hours] > 800, "High Risk", IF([Total Downtime Hours] <= 800 && [Total Downtime Hours] >= 400, "Medium Risk", "Low Risk"))
			
			```
		displayFolder: Rank
		lineageTag: 396fd6d3-ade6-43cf-80de-b6cdbc675134

	measure 'Rank Plant by Defect Qty' =
			
			VAR topPlantDefectQty = IF(ISINSCOPE(Plant[Plant Location]),(RANKX(ALL(Plant[Plant Location]), [Total Defect Qty], ,DESC)))
			VAR bottomPlantDefectQty = IF(ISINSCOPE(Plant[Plant Location]),(RANKX(ALL(Plant[Plant Location]), [Total Defect Qty], ,ASC)))
			
			VAR ranking = IF(SELECTEDVALUE(TopBottom[Value]) = "Top", topPlantDefectQty, bottomPlantDefectQty)
			RETURN IF(ranking <= 'Top N Parameter'[Top N Parameter Value], [Total Defect Qty])
		formatString: 0
		displayFolder: Rank
		lineageTag: b10fc0c6-5638-4a40-8615-c8e2fb41fa5a

	measure 'Rank plant by DownTime Hrs' =
			
			VAR topPlantDownTimeHrs = IF(ISINSCOPE(Plant[Plant Location]),(RANKX(ALL(Plant[Plant Location]), [Total Downtime Hours], ,DESC)))
			VAR bottomPlantDownTimeHrs = IF(ISINSCOPE(Plant[Plant Location]),(RANKX(ALL(Plant[Plant Location]), [Total Downtime Hours], ,ASC)))
			
			VAR ranking = IF(SELECTEDVALUE(TopBottom[Value]) = "Top", topPlantDownTimeHrs, bottomPlantDownTimeHrs)
			
			RETURN IF(ranking <= 'Top N Parameter'[Top N Parameter Value], [Total Downtime Hours])
		displayFolder: Rank
		lineageTag: af77f256-1f7a-4f48-97dd-9457b703d1ef

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Column1
		dataType: string
		isHidden
		lineageTag: 003217af-ee95-49ff-9762-fb13827a8b8c
		summarizeBy: none
		sourceColumn: Column1

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition _Calculations = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

