table Defect
	lineageTag: 0f82b546-9a02-4426-9e35-4ae5882ed4cf

	column DefectID
		dataType: string
		lineageTag: f1fcd6ff-0847-4844-b26d-d435d0e868b4
		summarizeBy: none
		sourceColumn: DefectID

		annotation SummarizationSetBy = Automatic

	column Defect
		dataType: string
		lineageTag: f9fe7013-d272-427d-8af5-d9d12f0f6e5a
		summarizeBy: none
		sourceColumn: Defect

		annotation SummarizationSetBy = Automatic

	partition Defect = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\HP\OneDrive\Desktop\Supplier_DA\SUPPLIER INSIGHTS\supplier data.xlsx"), null, true),
				    #"Supplier Quality_Sheet" = Source{[Item="Supplier Quality",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"Supplier Quality_Sheet", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Date", type date}, {"Vendor", type text}, {"Plant Location", type text}, {"Category", type text}, {"Material Type", type text}, {"Defect Type", type text}, {"Defect", type text}, {"Total Defect Qty", Int64.Type}, {"Total Downtime Minutes", Int64.Type}}),
				    #"Removed Other Columns" = Table.SelectColumns(#"Changed Type",{"Defect"}),
				    #"Added Index" = Table.AddIndexColumn(#"Removed Other Columns", "Index", 1, 1, Int64.Type),
				    #"Reordered Columns" = Table.ReorderColumns(#"Added Index",{"Index", "Defect"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Reordered Columns",{{"Index", "DefectID"}}),
				    #"Removed Duplicates" = Table.Distinct(#"Renamed Columns", {"Defect"}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Removed Duplicates",{{"DefectID", type text}})
				in
				    #"Changed Type1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

