table 'Defect Type'
	lineageTag: bd2a3436-275f-4f75-8196-9b0177339416

	column DefectTypeID
		dataType: string
		lineageTag: b2b02dfb-df45-49f6-ae01-331376801193
		summarizeBy: none
		sourceColumn: DefectTypeID

		annotation SummarizationSetBy = Automatic

	column 'Defect Type'
		dataType: string
		lineageTag: 279ddb6b-6cdd-432a-a7ad-d1f65d29c615
		summarizeBy: none
		sourceColumn: Defect Type

		annotation SummarizationSetBy = Automatic

	partition 'Defect Type' = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\HP\OneDrive\Desktop\Supplier_DA\SUPPLIER INSIGHTS\supplier data.xlsx"), null, true),
				    #"Supplier Quality_Sheet" = Source{[Item="Supplier Quality",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"Supplier Quality_Sheet", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Date", type date}, {"Vendor", type text}, {"Plant Location", type text}, {"Category", type text}, {"Material Type", type text}, {"Defect Type", type text}, {"Defect", type text}, {"Total Defect Qty", Int64.Type}, {"Total Downtime Minutes", Int64.Type}}),
				    #"Removed Other Columns" = Table.SelectColumns(#"Changed Type",{"Defect Type"}),
				    #"Added Index" = Table.AddIndexColumn(#"Removed Other Columns", "Index", 1, 1, Int64.Type),
				    #"Renamed Columns" = Table.RenameColumns(#"Added Index",{{"Index", "DefectTypeID"}}),
				    #"Reordered Columns" = Table.ReorderColumns(#"Renamed Columns",{"DefectTypeID", "Defect Type"}),
				    #"Removed Duplicates" = Table.Distinct(#"Reordered Columns", {"Defect Type"}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Removed Duplicates",{{"DefectTypeID", type text}})
				in
				    #"Changed Type1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

