table 'Material Type'
	lineageTag: 9afef443-a353-4ff7-9382-f299db9981a3

	column MaterialID
		dataType: string
		lineageTag: 1dbcb449-6d02-4df3-8702-0dc7b1cd5294
		summarizeBy: none
		sourceColumn: MaterialID

		annotation SummarizationSetBy = Automatic

	column 'Material Type'
		dataType: string
		lineageTag: a0171519-05b4-4a0b-9320-5a95e119b7d3
		summarizeBy: none
		sourceColumn: Material Type

		annotation SummarizationSetBy = Automatic

	partition 'Material Type' = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\HP\OneDrive\Desktop\Supplier_DA\SUPPLIER INSIGHTS\supplier data.xlsx"), null, true),
				    #"Supplier Quality_Sheet" = Source{[Item="Supplier Quality",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"Supplier Quality_Sheet", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Date", type date}, {"Vendor", type text}, {"Plant Location", type text}, {"Category", type text}, {"Material Type", type text}, {"Defect Type", type text}, {"Defect", type text}, {"Total Defect Qty", Int64.Type}, {"Total Downtime Minutes", Int64.Type}}),
				    #"Removed Other Columns" = Table.SelectColumns(#"Changed Type",{"Material Type"}),
				    #"Added Index" = Table.AddIndexColumn(#"Removed Other Columns", "Index", 1, 1, Int64.Type),
				    #"Reordered Columns" = Table.ReorderColumns(#"Added Index",{"Index", "Material Type"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Reordered Columns",{{"Index", "MaterialID"}}),
				    #"Removed Duplicates" = Table.Distinct(#"Renamed Columns", {"Material Type"}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Removed Duplicates",{{"MaterialID", type text}})
				in
				    #"Changed Type1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

