table Plant
	lineageTag: 79f26844-0815-483d-b34f-dce7f6ee4aa8

	column PlantID
		dataType: string
		lineageTag: 0ead19df-40cb-43b4-91f8-1ad6dcd61bed
		summarizeBy: none
		sourceColumn: PlantID

		annotation SummarizationSetBy = Automatic

	column 'Plant Location'
		dataType: string
		lineageTag: 94cf20c2-cdae-4564-bea3-3d2004562d93
		summarizeBy: none
		sourceColumn: Plant Location

		annotation SummarizationSetBy = Automatic

	partition Plant = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\HP\OneDrive\Desktop\Supplier_DA\SUPPLIER INSIGHTS\supplier data.xlsx"), null, true),
				    #"Supplier Quality_Sheet" = Source{[Item="Supplier Quality",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"Supplier Quality_Sheet", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Date", type date}, {"Vendor", type text}, {"Plant Location", type text}, {"Category", type text}, {"Material Type", type text}, {"Defect Type", type text}, {"Defect", type text}, {"Total Defect Qty", Int64.Type}, {"Total Downtime Minutes", Int64.Type}}),
				    #"Removed Other Columns" = Table.SelectColumns(#"Changed Type",{"Plant Location"}),
				    #"Added Index" = Table.AddIndexColumn(#"Removed Other Columns", "Index", 1, 1, Int64.Type),
				    #"Reordered Columns" = Table.ReorderColumns(#"Added Index",{"Index", "Plant Location"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Reordered Columns",{{"Index", "PlantID"}}),
				    #"Removed Duplicates" = Table.Distinct(#"Renamed Columns", {"Plant Location"}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Removed Duplicates",{{"PlantID", type text}})
				in
				    #"Changed Type1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

