table Vendor
	lineageTag: 0ee5b8f8-ff36-419e-bbe9-7e93f1771487

	column VendorID
		dataType: string
		lineageTag: 9e4bf5f1-7703-4eff-b374-b3b99b51e6f8
		summarizeBy: none
		sourceColumn: VendorID

		annotation SummarizationSetBy = Automatic

	column Vendor
		dataType: string
		lineageTag: f0e21528-c4b4-43ca-a39b-6b705a9b5f85
		summarizeBy: none
		sourceColumn: Vendor

		annotation SummarizationSetBy = Automatic

	partition Vendor = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\HP\OneDrive\Desktop\Supplier_DA\SUPPLIER INSIGHTS\supplier data.xlsx"), null, true),
				    #"Supplier Quality_Sheet" = Source{[Item="Supplier Quality",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"Supplier Quality_Sheet", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Date", type date}, {"Vendor", type text}, {"Plant Location", type text}, {"Category", type text}, {"Material Type", type text}, {"Defect Type", type text}, {"Defect", type text}, {"Total Defect Qty", Int64.Type}, {"Total Downtime Minutes", Int64.Type}}),
				    #"Removed Other Columns" = Table.SelectColumns(#"Changed Type",{"Vendor"}),
				    #"Removed Duplicates" = Table.Distinct(#"Removed Other Columns"),
				    #"Added Index" = Table.AddIndexColumn(#"Removed Duplicates", "Index", 1, 1, Int64.Type),
				    #"Reordered Columns" = Table.ReorderColumns(#"Added Index",{"Index", "Vendor"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Reordered Columns",{{"Index", "VendorID"}}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Renamed Columns",{{"VendorID", type text}})
				in
				    #"Changed Type1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

